### ISSUE TITLE
Repetitive paste and text selection

### ISSUE THREAD

**Issue by kenn-4** [keymapperorg/KeyMapper#1060] opened 2022-06-28 20:02 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
Text pasting actions are repetitive despite settings for single action. When trigger is sent, such as fingerprint swipe, the text copied is pasted twice. For text selection, whole line is selected instead of last word.
**To Reproduce**
Set paste trigged as fingerprint swipe up on Huawei honor 6x (no root). Select trigger is set as swipe left.
Upload a backup of your keymaps. [Follow the guide here](https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)
**Expected behavior**
Paste action shoot send just one instance of the word/letter.
**Screenshots**
![Screenshot_20220628-230001.jpg](https://user-images.githubusercontent.com/85829244/176274047-e8ee374e-2ad5-4d60-911f-ea9fb67a9ab7.jpg)
**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
Huawei honor 6x
 - Android version: [e.g. Android 10]
8
**Additional context**

**Comment by sds100** [comment] 2022-07-06 13:36
Hi @kenn-4 ! I can _not_ reproduce the double-pasting issue. But I think I can reproduce the selecting the whole line and not the word issue. This only happens if the cursor is at the end of the line but if the cursor is in the middle of the word then it works fine. Same for you?

**Comment by kenn-4** [comment] 2022-07-07 23:45
Tried it. It's true, when not at the end of the line, the cursor selects a
single word. A shame about the double paste; would've been great using that
option with the fingerprint sensor. On the same note, will you be adding
options for tapping the sensor, better yet, using it for for
scrolling purposes? That would give the feel of a mouse wheel. Great tool,
if I haven't mentioned that yet.

**Comment by sds100** [comment] 2022-07-08 11:36
@kenn-4 I can't add any more fingerprint sensor gestures because the Android API is very basic. It only tells the app that it has been swiped in the 4 directions. Apps don't get any more fine grained information.

**Comment by sds100** [comment] 2022-07-08 11:37
Closing this because it can't be reproduced but fixing this other bug #1062

**Closed by sds100** 2022-07-08 11:37 UTC
Labels: bug
