### ISSUE TITLE
Do not Disturb Permission request on device that has it disabled

### ISSUE THREAD

**Issue by DominicBen** [keymapperorg/KeyMapper#1175] opened 2023-10-09 17:50 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] test on Android TV emulator
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Describe the bug**
My phone does not have built in volume buttons. When attempting to add the Action Volume up to any button, I am prompted to enable Do Not Distirb permissions for the app. My phone does not have do not disturb enabled, So i am redirected to the settings page, without anything changing

**To Reproduce**
Create Action to change volume, Bind to any function
When asked to fix Do not Disturb, click fix.
If do not disturb is disabled on your device, you our of luck.

**Expected behavior**
I expect the app to have some setting that would allow users to bypass this requirement if they do not have do not disturb as an available setting on their phone.

**Screenshots**
![image](https://github.com/keymapperorg/KeyMapper/assets/1526245/d4ec7b1a-04f8-4726-9bc5-e50b421b305c)

![image](https://github.com/keymapperorg/KeyMapper/assets/1526245/a29daaec-247b-4388-83e0-d53e6a6bc0cd)

![image](https://github.com/keymapperorg/KeyMapper/assets/1526245/85ce9b52-ab97-4900-b429-38756791174b)

**Smartphone (please complete the following information):**
 - Device: 902kc
 - Android version: Android 8
 
https://github.com/keymapperorg/KeyMapper/issues/1016 
This issue is somewhat related, but solves a problem with the volume buttons, rather than the volume action itself

Volume control works with other keymapping apps, but i personally really like this app, so i would love for this to work.

**Comment by BloodRaven0** [comment] 2024-01-02 06:56
I'm not sure if it's related, but on Android TV 13, I can't map action to mute without this error message popping up. The keymap doesn't even try to send the command, it's just disabled, and clicking "fix" understandably returns an error that the DND menu wasn't found (ATV doesn't have such a menu).

**Comment by sds100** [comment] 2024-07-07 20:53
Duplicate of #526

**Closed by sds100** 2024-07-07 20:53 UTC
Labels: bug
