### ISSUE TITLE
Can't activate Notifications

### ISSUE THREAD

**Issue by isrgish** [keymapperorg/KeyMapper#1185] opened 2023-11-02 19:26 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
I can't activate any notifications for the app. The opton is greyed out.

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here]
[keymapper_mappings-new.zip](https://github.com/keymapperorg/KeyMapper/files/13243763/keymapper_mappings-new.zip)
[key_mapper_report_20231102-151616.zip](https://github.com/keymapperorg/KeyMapper/files/13243764/key_mapper_report_20231102-151616.zip)

(https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**
![Screenshot_20231102-151953_Settings](https://github.com/keymapperorg/KeyMapper/assets/35469435/1a728e30-c83f-4c46-b65c-b141131e8dac)
![Screenshot_20231102-151936_Settings](https://github.com/keymapperorg/KeyMapper/assets/35469435/4533064a-a489-444c-84d8-0f46de3d6218)
![Screenshot_20231102-151925_Settings](https://github.com/keymapperorg/KeyMapper/assets/35469435/820ba971-e605-450d-b2a3-6f731d2588ad)

**Smartphone (please complete the following information):**
 - Device: Lenovo Legion Y700 running Phh-Treble GSI
 - Android version: 13

**Additional context**

**Comment by sds100** [comment] 2024-06-12 11:23
duplicate of #1219

**Closed by sds100** 2024-06-12 11:23 UTC
Labels: bug
