### ISSUE TITLE
How do I set permissions with do not disturb adb

### ISSUE THREAD

**Issue by ooh3837** [keymapperorg/KeyMapper#1135] opened 2023-04-24 14:11 UTC
How do I set permissions with do not disturb adb

the app needs permission to change the do not disturb state
error message appears

But there is no button to set on the phone
I think you need to set permissions using adb.

**Comment by sds100** [comment] 2024-07-07 20:52
Duplicate of #526

**Closed by sds100** 2024-07-07 20:52 UTC
Labels: bug
