### ISSUE TITLE
Add bixby key support

### ISSUE THREAD

**Issue by ArjhanToteck** [keymapperorg/KeyMapper#1287] opened 2024-09-02 03:27 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

A closed source app called Button Mapper is able to use the Bixby key, it would be nice if this app could support it.

**Comment by sds100** [comment] 2024-09-04 10:27
Duplicate of #118

**Closed by sds100** 2024-09-04 10:27 UTC
Labels: enhancement
