### ISSUE TITLE
Binding key combination on volume key issue

### ISSUE THREAD

**Issue by Damglador** [keymapperorg/KeyMapper#1302] opened 2024-09-21 23:08 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Describe the bug**
So normally holding down a volume key repeatedly increases volume, but it stops doing that if there is a key combination bonded to it in Key Mapper. Wouldn't be an issue, if fixing it in Key Mapper, by binding volume button to repeatedly increase volume, didn't cause it to show even if you're trying to make a screenshot.

**To Reproduce**
Keymap with 2 keys and this configuration:
- Short press
- At the same time
- Vol down is first in the list
- Does anything

My keymap:
[mappings_new.zip](https://github.com/user-attachments/files/17085960/mappings_new.zip)
it has volume down and additional button on my phone bonded to screenshot, can be reproduced with volume down and fingerprint reader and probably other buttons.

**Expected behavior**
Volume key should continue doing its thing and keep holding down functionality.

**Smartphone (please complete the following information):**
 - Device: Ulefone Armor 21
 - Android version: Android 14

**Comment by ChocolateLoverRaj** [comment] 2024-09-22 02:49
This is happening to me too on a Pixel 2 XL. I want a short press of vol up + vol down at the same time to play/pause media. If vol down is on top in the mapping, I can't press and hold vol down to increase volume. If vol up is on top in the mapping, I can't press and hold vol up to increase volume.

**Comment by sds100** [comment] 2024-09-22 08:40
Hi, I think I understand the problem and its case where intended behavior for some people is not what others want 😅. So this issue exists for two reasons: some people want to repeat some action while holding down two buttons at once. And I would need to introduce some configurable time-window or delay where while holding down the first key, you must press the second key, otherwise the mapping will be ignored and will do it's normal action. There isn't actually a way I could tell it to do this normal action because the DOWN key event has already fired so I'd also have to simulate repeatedly decreasing the volume like the system. This wouldn't work for other keys.

So the solution would be to implement some sort of "fix" above. I've managed to implement this behavior in Key Mapper ![key_maps-volume-fix.zip](https://github.com/user-attachments/files/17088833/key_maps-volume-fix.zip)

**Comment by sds100** [comment] 2024-09-29 12:08
Closing this because there is a solution in Key Mapper already and introducing this new behavior may break a lot of other people's mappings.

**Closed by sds100** 2024-09-29 12:08 UTC
Labels: bug
