### ISSUE TITLE
Can order be ignored currently? ctrl+alt+1 = alt+ctrl+1?

### ISSUE THREAD

**Issue by gzyguo** [keymapperorg/KeyMapper#940] opened 2022-02-28 15:19 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

Currently I have to create pairs of triggers for this reason, it is the modifier keys to keep their order in mind in practice is a burden for me, hope there is a switch to turn this discrimination off.

**Comment by sds100** [comment] 2022-06-21 22:08
Duplicate of #591

**Closed by sds100** 2022-06-21 22:08 UTC
Labels: enhancement, key map
