### ISSUE TITLE
Crash: File manager can not be found when doing automatic backups

### ISSUE THREAD

**Issue by andreyoleynik** [keymapperorg/KeyMapper#1183] opened 2023-10-22 18:06 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
When I press "Automatically back up mappings to a specified location" app crashes. After restart the app I can't start service again, only restart device.

**To Reproduce**

Try to setup autosave. Also Can't save from main screen, but without exception. Load works good, see file chose dialog

**Expected behavior**

**Screenshots**

See logcat:
FATAL EXCEPTION: main
                                                                                                    Process: io.github.sds100.keymapper, PID: 7409
                                                                                                    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT typ=todo/todo (has extras) }
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5283)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
                                                                                                    	at androidx.core.app.b$b.b(SourceFile:1)
                                                                                                    	at androidx.core.app.b.y(SourceFile:1)
                                                                                                    	at androidx.activity.ComponentActivity$b.f(SourceFile:1)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$a.b(SourceFile:1)
                                                                                                    	at androidx.fragment.app.Fragment$a.b(SourceFile:1)
                                                                                                    	at androidx.activity.result.c.a(SourceFile:1)
                                                                                                    	at io.github.sds100.keymapper.settings.MainSettingsFragment.populatePreferenceScreen$lambda$28$lambda$7$lambda$6(Unknown Source:34)
                                                                                                    	at io.github.sds100.keymapper.settings.MainSettingsFragment.q(SourceFile:1)
                                                                                                    	at io.github.sds100.keymapper.settings.r.a(SourceFile:1)
                                                                                                    	at androidx.preference.Preference.c0(SourceFile:1)
                                                                                                    	at androidx.preference.Preference.d0(SourceFile:1)
                                                                                                    	at androidx.preference.Preference$a.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7153)
                                                                                                    	at android.view.View.performClickInternal(View.java:7126)
                                                                                                    	at android.view.View.access$3500(View.java:803)
                                                                                                    	at android.view.View$PerformClick.run(View.java:27540)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7422)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Smartphone (please complete the following information):**
 - Device: Car device with Android 10 (looks like). Tried to install a lot of File managers (XPlore, Total commander, Files and other)
 - Android version: Android 10

**Additional context**
Loading dialog works good, but crashes on saving. Doesn't depend on how many file managers installed.

**Comment by sds100** [comment] 2024-07-07 21:25
I'm not able to reproduce this. I installed MiXplorer and I was able to select a location to save. Can you try the latest testing version because I changed something that may be indirectly related. You can read how to get this build here https://docs.keymapper.club/contributing/#becoming-a-tester.

**Comment by sds100** [comment] 2024-08-04 19:36
Closing because I fixed the stacktrace and this is a duplicate of #1203

**Closed by sds100** 2024-08-04 19:36 UTC
Labels: bug
