### ISSUE TITLE
Realme killed keymapper 

### ISSUE THREAD

**Issue by Keymapperuser** [keymapperorg/KeyMapper#969] opened 2022-04-11 15:20 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]
Please have a permanent solution for ur phone killed keymapper.
**Additional context**

**Comment by jambl3r** [comment] 2022-04-24 09:08
Closed as duplicate of https://github.com/keymapperorg/KeyMapper/issues/248

**Closed** 2022-04-24 09:08 UTC
Labels: bug

**Comment by NotAkash099** [comment] 2022-05-24 06:00
Hey keymapper can u solve problem that my phn killed keymapper??
