### ISSUE TITLE
Crashisg

### ISSUE THREAD

**Issue by Arvgaming** [keymapperorg/KeyMapper#936] opened 2022-02-17 20:33 UTC
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**
I have trying to use after a 5h then I start so it doesn't work so I see some problem I I fixed all but one left.it says it has been crashed so go turn off and again turn on accessibility so I do that but ot doesn't repair I tried many times but nothing happen.

**Comment by jambl3r** [comment] 2022-02-21 01:27
Closed as duplicate of https://github.com/keymapperorg/KeyMapper/issues/188
Please join the discord at keymapper.club and seek help there

**Closed by jambl3r** 2022-02-21 01:27 UTC
Labels: bug
